#!/bin/bash

convert_path()
{
    echo ${*//C:/$WINEPREFIX/drive_c/}
}

export WINEDEBUG=-all
export WINEPREFIX=/path/to/SteamLibrary/steamapps/compatdata/244850/pfx
export PATH=/path/to/SteamLibrary/steamapps/common/Proton\ 7.0/dist/bin:$PATH

if [ $# -gt 0 ]; then
    $@
else
    $SHELL
fi
